package hardware;

import exceptions.IntensityOutOfBoundException;
import helper.Intensity;

public class StreetLamp {
    private final static int MIN_INTENSITY = 0;     // Guard value
    private final static int BASE_INTENSITY = 24;   // Guard value
    private final static int MAX_INTENSITY = 100;   // Guard value

    private static int count = 0;
    private int id;
    private int intensity;
    private Street street;

    private StreetLamp next;    // Reference to the next Street Lamp
    private StreetLamp prev;    // Reference to the prev Street Lamp

    private int indexNext;
    private int indexPrev;

    private int[] intensities = Intensity.getIntensitiesInt();

    public StreetLamp(Street street, int intensity) throws IntensityOutOfBoundException {
        if (intensity < MIN_INTENSITY || intensity > MAX_INTENSITY) {
            throw new IntensityOutOfBoundException(intensity);
        } else {
            this.intensity = intensity;
            this.street = street;
            id = count;
            count++;
        }
        this.prev = null;
        this.next = null;
    }

    //TODO transorm it into a builder factory (o come cazzo si chiama) if you want
    public StreetLamp(int intensity) throws IntensityOutOfBoundException {
        if (intensity < MIN_INTENSITY || intensity > MAX_INTENSITY) {
            throw new IntensityOutOfBoundException(intensity);
        } else {
            this.intensity = intensity;
            id = count;
            count++;
        }
        this.prev = null;
        this.next = null;
    }

    public int getIntensity() {
        return intensity;
    }

    public void setIntensity(int intensity) {
        if (intensity >= MIN_INTENSITY && intensity <= MAX_INTENSITY)
            this.intensity = intensity;
    }

    /**
     * This method lets the current Street Lamp to communicate with the next one
     * @param intensity is a value generated by a combination of parameters, such as velocity
     */
    /*private void sendToNextStreetLamp(int intensity) {
        Street.currentSLNext = Street.currentSLNext.getNext();
        assert Street.currentSLNext != null;
        if (intensity >= BASE_INTENSITY) {
            Street.currentSLNext.setIntensity(intensity);
            if (Street.currentSLNext.getNext() != null && intensity > BASE_INTENSITY) {
                indexNext--;
                sendToNextStreetLamp(intensities[indexNext]);
            }
        }
    }*/

    /**
     * This method lets the current Street Lamp to communicate with the previous one
     * @param intensity is a value generated by a combination of parameters, such as velocity
     */
    /*private void sendToPrevStreetLamp(int intensity) {
        Street.currentSLPrev = Street.currentSLPrev.getPrev();
        if (intensity >= BASE_INTENSITY) {
            Street.currentSLPrev.setIntensity(intensity);
            if (Street.currentSLPrev.getPrev() != null && intensity > BASE_INTENSITY) {
                indexPrev--;
                sendToPrevStreetLamp(intensities[indexPrev]);
            }
        }
    }*/

    /**
     * Add a previous Street Lamp to the current one
     * @param p the Street Lamp to add
     */
    public void addPrevStreetLamp(StreetLamp p) {
        this.prev = p;
    }

    private StreetLamp getPrev() {
        return prev;
    }

    /**
     * Add a next Street Lamp to the current one
     * @param n the Street Lamp to add
     */
    public void addNextStreetLamp(StreetLamp n) {
        this.next = n;
    }

    private StreetLamp getNext() {
        return next;
    }


    @Override
    public boolean equals(Object obj) {
        return obj instanceof StreetLamp && ((StreetLamp) obj).id == id;
    }

    @Override
    public String toString() {
        String s = "";
        s += id + ":" + intensity + " ";

        return s;
    }

    /**
     * This method is called when a sensor is activated (i.e. when it detect a car or a pedestrian)
     * It sets at the maximum intensity the current Street Lamps and the next two; it goes back to
     * the previous Street Lamps and goes on to the next ones
     */
    /*public void sensorDetected() {
        indexPrev = 6;

        Street.currentSLPrev = this;
        Street.currentSLPrev.setIntensity(intensities[indexPrev]);
        if (Street.currentSLPrev.getPrev() != null) {
            indexPrev--;
            sendToPrevStreetLamp(intensities[indexPrev]);
        }

        indexNext = 6;

        Street.currentSLNext = this;
        // Turn on 3 street lamps
        Street.currentSLNext.setIntensity(intensities[indexNext]);
        for (int i = 0; i < 2 && Street.currentSLNext.getNext() != null; i++) {
            Street.currentSLNext = Street.currentSLNext.getNext();
            Street.currentSLNext.setIntensity(intensities[indexNext]);
        }
        if (Street.currentSLNext.getNext() != null) {
            indexNext--;
            sendToNextStreetLamp(intensities[indexNext]);
        }
    }*/
}